name: 🐛 Bug Report
description: Report a bug or issue with the rich text editor
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize editor with '...'
        2. Click on '....'
        3. Type '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { Editor } from 'modern-rich-text-editor';

        const editor = new Editor('#editor', {
          // your options
        });

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the editor are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s)
      description: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What browser version?
      placeholder: e.g., Chrome 120.0.6099.109

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error logs, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have tested this with the latest version
          required: true
        - label: I have provided a minimal reproduction example
          required: false
